const { getPets } = require("../controlers/controllersPets/getPets");
const { getUsers } = require("../controlers/controllersUsers/getUsers");
const {
  getProvincias,
} = require("../controlers/controllersProvincias/getProvincias");

const validateDataBase = async (req, res, next) => {
  const pets = await getPets();
  const users = await getUsers();
  const provincias = await getProvincias();

  if (pets.length > 0 || users.length > 0 || provincias.length > 0) {
    return res.status(200).json("YA HAY SE CARGARON DATOS EN LA BASE DE DATOS");
  }
  next();
};
const examplePets = [
  {
    name: "fido",
    age: 2,
    description: "muy tranquilofido. Es un perro muy grande pero re cariñoso",
    image:
      "https://res.cloudinary.com/dg80wnkdc/image/upload/v1677500837/PFimages/razas-de-perro-toy-t.jpg_po2qpi.webp",
    size: "grande",
    animal: "perros",
    healthBook: true,
    sex: "femenino",
    province: "BuenosAires",
    location: "SanFernando",
  },
  {
    name: "bugs bunny",
    age: 11,
    description: "re divertido",
    image:
      "https://res.cloudinary.com/dg80wnkdc/image/upload/v1677500846/PFimages/razas_de_conejos_enanos_o_toy_24086_600_square_r1nbzv.jpg",
    size: "pequeño",
    animal: "roedores",
    healthBook: false,
    sex: "masculino",
    province: "Cordoba",
    location: "Villa Warcalde",
  },
  {
    name: "manuelita",
    age: 20,
    description: "como come!! lenta la pobre pero se la aguanta",
    image:
      "https://res.cloudinary.com/dg80wnkdc/image/upload/v1677500851/PFimages/la_tortuga_como_mascota_24473_orig_b0iuv6.jpg",
    size: "pequeño",
    animal: "roedores",
    healthBook: false,
    sex: "masculino",
    province: "Mendoza",
    location: "La Cieneguita",
  },
  {
    name: "pepito",
    age: 8,
    description: "el mejor amigo del solitario",
    size: "pequeño",
    animal: "aves",
    healthBook: false,
    sex: "femenino",
    province: "San Luis",
    location: "Cerro de la Cruz",
    active: "false",
  },
];
const ejemplosUsers = [
  {
    name: "felipe",
    image:
      "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    email: "pepe@gmail.com",
    password: 12343,
    rol: "usuario",
    logged: false,
  },
  {
    name: "pepita",
    image:
      "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png",
    email: "pepe@gmail.com",
    password: 12345,
    rol: "administrador",
    logged: false,
  },
];
const ejemploProvincias = [
  {
    name: "Misiones",
  },
  {
    name: "San Luis",
  },
  {
    name: "San Juan",
  },
  {
    name: "Entre Ríos",
  },
  {
    name: "Santa Cruz",
  },
  {
    name: "Río Negro",
  },
  {
    name: "Chubut",
  },
  {
    name: "Córdoba",
  },
  {
    name: "Mendoza",
  },
  {
    name: "La Rioja",
  },
  {
    name: "Catamarca",
  },
  {
    name: "La Pampa",
  },
  {
    name: "Santiago del Estero",
  },
  {
    name: "Corrientes",
  },
  {
    name: "Santa Fe",
  },
  {
    name: "Tucumán",
  },
  {
    name: "Neuquén",
  },
  {
    name: "Salta",
  },
  {
    name: "Chaco",
  },
  {
    name: "Formosa",
  },
  {
    name: "Jujuy",
  },
  {
    name: "Ciudad Autónoma de Buenos Aires",
  },
  {
    name: "Buenos Aires",
  },
  {
    name: "Tierra del Fuego",
  },
];
const ejemploLocalidades = [
  [
    "Apóstoles",
    "Tres Capones",
    "Mártires",
    "Santiago de Liniers",
    "San Pedro",
    "Campo Grande",
    "Puerto Rico",
    "Montecarlo",
    "El Soberbio",
    "Cerro Corá",
    "Garupá",
    "Santa Ana",
    "Corpus",
    "Gobernador Roca",
    "Posadas",
    "Panambí",
    "Hipólito Irigoyen",
    "Profundidad",
    "Azara",
    "Colonia Aurora",
    "Fachinal",
    "El Alcázar",
    "Capioví",
    "Santo Pipo",
    "Colonia Polana",
    "Gobernador López",
    "Jardín América",
    "Caa Yarí",
    "Olegario V. Andrade",
    "Cerro Azul",
    "General J. J. Urquiza",
    "Alba Posse",
    "Los Helechos",
    "San Vicente",
    "Mojón Grande",
    "Gral. Alvear",
    "San Javier",
    "Ruiz de Montoya",
    "Santa María",
    "Guaraní",
    "San Martín",
    "San José",
    "Puerto Esperanza",
    "Itacaruaré",
    "Almafuerte",
    "Colonia Alberdi",
    "Leandro N. Alem",
    "Colonia Delicia",
    "Bernardo de Irigoyen",
    "Colonia Victoria",
    "25 de Mayo",
    "Oberá",
    "Iguazú",
    "Leoni",
    "Caraguatay",
    "Campo Viera",
    "Dos Arroyos",
    "Concepción de la Sierra",
    "Arroyo del Medio",
    "9 de Julio",
    "Bonpland",
    "San Ignacio",
    "Comandante A. Guacurary",
    "San Antonio",
    "Aristóbulo del Valle",
    "Ameghino",
    "Campo Ramón",
    "Eldorado",
    "Puerto Piray",
    "Garuhapé",
    "Colonia Wanda",
    "Dos de Mayo",
    "Candelaria",
    "Loreto",
    "Libertad",
  ],
  [
    "Zanjitas",
    "Beazley",
    "Balde",
    "Fraga",
    "P. de los Funes",
    "Carolina",
    "San Francisco",
    "Merlo",
    "Juana Koslay",
    "Batavia",
    "Ranqueles",
    "Alto Pencoso",
    "Las Aguadas",
    "San Martin",
    "Leandro N. Alem",
    "La Calera",
    "La Punilla",
    "Fortin el Patria",
    "Lujan",
    "Quines",
    "Las Vertientes",
    "Paso Grande",
    "San Luis",
    "El Trapiche",
    "Navia",
    "Desaguadero",
    "Villa Mercedes",
    "Candelaria",
    "Alto Pelado",
    "Las Lagunas",
    "Las Chacras",
    "V, de Praga",
    "Villa del Carmen",
    "San Pablo",
    "Renca",
    "Tilisarao",
    "Los Molles",
    "V, Gral, Roca",
    "V, de la Quebrada",
    "Nogoli",
    "Carpinteria",
    "La Toma",
    "Juan Llerena",
    "Concaran",
    "Talita",
    "Sta Rosa del Conlara",
    "Villa Larca",
    "Papagayos",
    "Naschel",
    "Justo Daract",
    "Saladillo",
    "Bagual",
    "Arizona",
    "Buena Esperanza",
    "Union",
    "San Jeronimo",
    "El Volcan",
    "Estancia Grande",
    "La Punta",
    "Nueva Galia",
    "Fortuna",
    "Anchorena",
    "Juan Jorba",
    "Lavaisse",
    "San Jose del Morro",
    "Cortaderas",
    "Lafinur",
  ],
  [
    "Iglesia",
    "Valle Fértil",
    "Ullum",
    "Albardón",
    "Zonda",
    "Chimbas",
    "Rivadavia",
    "Santa Lucía",
    "Rawson",
    "Pocito",
    "Sarmiento",
    "Jáchal",
    "Calingasta",
    "25 de Mayo",
    "San Juan",
    "9 de Julio",
    "San Martín",
    "Angaco",
    "Caucete",
  ],
  [
    "Villaguay",
    "San Salvador",
    "Nogoyá",
    "Tala",
    "La Paz",
    "Concordia",
    "Federal",
    "Gualeguaychú",
    "Islas del Ibicuy",
    "Victoria",
    "Diamante",
    "Uruguay",
    "Paraná",
    "Colón",
    "Gualeguay",
    "Federación",
    "Feliciano",
  ],
  [
    "Magallanes",
    "Corpen Aike",
    "Lago Buenos Aires",
    "Deseado",
    "Río Chico",
    "Lago Argentino",
    "Güer Aike",
  ],
  [
    "Cipolletti",
    "Ing. Jacobacci",
    "El Bolson",
    "San Carlos de Bariloche",
    "Guardia Mitre",
    "Gral. Roca",
    "Luis Beltran",
    "Gral. Conesa",
    "Choele Choel",
    "Lamarque",
    "Coronel Belisle",
    "Darwin",
    "Chimpay",
    "Chichinales",
    "Allen",
    "Cinco Saltos",
    "Campo Grande",
    "Contralmirante Cordero",
    "Mainque",
    "Catriel",
    "Dina Huapi",
    "Gral. Enrique Godoy",
    "Ingeniero Huergo",
    "Villa Regina",
    "Rìo Colorado",
    "El Manso",
    "San Javier",
    "Arroyo Ventana",
    "Laguna Blanca",
    "Pilquiniyeu",
    "Nahuel Niyeu",
    "Sierra Paileman",
    "Peñas Blancas",
    "Paso Flores",
    "Aguada Guzman",
    "Valle Azul",
    "Villa Llanquin",
    "Arroyo los Berros",
    "Rincon de Treneta",
    "Comico",
    "El Cain",
    "Cona Niyeu",
    "Yaminué",
    "El Cuy",
    "Aguada de Guerra",
    "Naupa Huen",
    "Colan Conhué",
    "Mencuen",
    "Ojos de Agua",
    "Clemente Onelli",
    "Pilquiniyeu del Limay",
    "Mamuel Choique",
    "Rio Chico",
    "Viedma",
    "Maquinchao",
    "Sierra Grande",
    "Pilcaniyeu",
    "San Antonio Oeste",
    "Comallo",
    "Los Menucos",
    "Valcheta",
    "Sierra Colorada",
    "Ministro Ramos Mexia",
    "Gral. Fdez. Oro",
    "Pomona",
    "Ñorquinco",
    "Cervantes",
    "Chipauquil",
    "Prahuaniyeu",
    "Aguada Cecilio",
  ],
  [
    "Buen Pasto",
    "Carrenleufú",
    "El Maitén",
    "Puerto Madryn",
    "Cholila",
    "Rawson",
    "28 de Julio",
    "Río Pico",
    "Alto Río Senguer",
    "Gobernador Costa",
    "El Hoyo",
    "Dolavon",
    "Trelew",
    "José de San Martín",
    "Aldea Beleiro",
    "Cushamen",
    "Dique Florentino Ameghino",
    "Doctor Ricardo Rojas",
    "Corcovado",
    "Puerto Pirámides",
    "Sarmiento",
    "Paso de Indios",
    "Gualjaina",
    "Aldea Epulef",
    "Facundo",
    "Gan Gan",
    "Lago Blanco",
    "Lagunita Salada",
    "Las Plumas",
    "Los Altares",
    "Paso del Sapo",
    "Telsen",
    "Trevelín",
    "Dr. Atilio Oscar Viglione",
    "Comodoro Rivadavia",
    "Lago Puelo",
    "Epuyén",
    "Gaiman",
    "Esquel",
    "Tecka",
    "Rada Tilly",
    "Río Mayo",
    "Camarones",
    "Cerro Centinela",
    "Colan Conhué",
    "Gastre",
  ],
  [
    "Ballesteros",
    "Río Bamba",
    "Río Ceballos",
    "Bialet Massé",
    "Jesús María",
    "La Cautiva",
    "La Granja",
    "Colazo",
    "Alcira",
    "Almafuerte",
    "Alpa Corral",
    "Alto Alegre",
    "Achiras",
    "Agua de Oro",
    "Amboy",
    "Alto de los Quebrachos",
    "Anisacate",
    "Arroyo los Patos",
    "Ambul",
    "Arias",
    "Atahona",
    "Ausonia",
    "Avellaneda",
    "Ballesteros Sud",
    "Balnearia",
    "Bañado de Soto",
    "Arroyito",
    "Bell Ville",
    "Berrotarán",
    "Bouwer",
    "Brinkmann",
    "Buchardo",
    "Bengolea",
    "Benjamín Gould",
    "Cavanagh",
    "Cañada de Luque",
    "Cabalango",
    "Villa del Dique",
    "Calmayo",
    "Camilo Aldao",
    "Caminiaga",
    "Canals",
    "Candelaria Sud",
    "Capilla de los Remedios",
    "Capilla del Carmen",
    "Capilla del Sitón",
    "Capitán General B. O'Higgins",
    "Carnerillo",
    "Carrilobo",
    "Cañada de Río Pinto",
    "Cerro Colorado",
    "Chaján",
    "Casa Grande",
    "Charbonier",
    "Chañar Viejo",
    "Chilibroste",
    "Churqui Cañada",
    "Charras",
    "Chuña",
    "Chuña Huasi",
    "Ciénaga del Coro",
    "Colonia Bremen",
    "Colonia Caroya",
    "Colonia las Cuatro Esquinas",
    "Colonia Marina",
    "Colonia Prosperidad",
    "Colonia Italiana",
    "Colonia Iturraspe",
    "Colonia Tirolesa",
    "Colonia las Pichanas",
    "Villa Yacanto",
    "Conlara",
    "Copacabana",
    "Coronel Moldes",
    "Corralito",
    "El Rastreador",
    "Costasacate",
    "Cruz de Caña",
    "Embalse",
    "Colonia San Bartolomé",
    "Cuesta Blanca",
    "Del Campillo",
    "Despeñaderos",
    "Devoto",
    "Diego de Rojas",
    "Dique Chico",
    "El Chacho",
    "El Crispín",
    "El Fortín",
    "Guatimozín",
    "El Manzano",
    "El Rodeo",
    "Esquina",
    "Estación General Paz",
    "Estación Juárez Celman",
    "Estancia de Guadalupe",
    "Estancia Vieja",
    "Etruria",
    "Falda del Carmen",
    "General Cabrera",
    "Guanaco Muerto",
    "Guasapampa",
    "James Craik",
    "Huerta Grande",
    "Huinca Renancó",
    "Idiazabal",
    "Impira",
    "La Calera",
    "La Cesira",
    "La Francia",
    "La Cruz",
    "La Cumbre",
    "La Paquita",
    "La Cumbrecita",
    "La Falda",
    "La Higuera",
    "La Laguna",
    "Laborde",
    "Laboulaye",
    "Laguna Larga",
    "Colonia San Pedro",
    "La Paisanita",
    "La Palestina",
    "La Pampa",
    "La Para",
    "La Paz",
    "La Playa",
    "La Población",
    "La Posta",
    "La Rancherita",
    "La Rinconada",
    "General Deheza",
    "La Serranita",
    "La Tordilla",
    "Las Acequias",
    "General Fotheringham",
    "Las Albahacas",
    "Las Arrias",
    "Las Bajadas",
    "Las Caleras",
    "Las Higueras",
    "Las Isletillas",
    "Las Junturas",
    "Las Rabonas",
    "Las Tapias",
    "Leones",
    "Los Cedros",
    "General Levalle",
    "Las Vertientes",
    "Leguizamón",
    "Los Cerrillos",
    "Los Chañaritos (C.D. Eje)",
    "Los Chañaritos",
    "Los Cocos",
    "Los Hornillos",
    "Los Mistoles",
    "Los Pozos",
    "Maquinista Gallini",
    "Marull",
    "Los Reartes",
    "Los Talares",
    "Los Zorros",
    "Lucio V. Mansilla",
    "Luque",
    "Luyaba",
    "Malagueño",
    "Malena",
    "Pampayasta Norte",
    "Panaholma",
    "Malvinas Argentinas",
    "Manfredi",
    "Potrero de Garay",
    "Matorrales",
    "Media Naranja",
    "Melo",
    "Mendiolaza",
    "Miramar",
    "Monte Buey",
    "Río de los Sauces",
    "Mi Granja",
    "Monte Cristo",
    "Monte de los Gauchos",
    "Monte Ralo",
    "Morrison",
    "Morteros",
    "Nicolás Bruzzone",
    "Obispo Trejo",
    "Olaeta",
    "Nono",
    "Oliva",
    "Olivares de San Nicolás",
    "Oncativo",
    "Ordóñez",
    "Pacheco de Melo",
    "Pasco",
    "Paso Viejo",
    "Pincen",
    "Piquillín",
    "Plaza Luxardo",
    "Porteña",
    "Pilar",
    "Plaza de Mercedes",
    "Pozo del Molle",
    "Pozo Nuevo",
    "Pueblo Italiano",
    "Puesto de Castro",
    "Quebracho Herrado",
    "Quilino",
    "Rafael García",
    "Ranqueles",
    "Rayo Cortado",
    "Reducción",
    "Rincón",
    "Río Cuarto",
    "Río Segundo",
    "Río Tercero",
    "Rosales",
    "Rosario del Saladillo",
    "Sacanta",
    "Sagrada Familia",
    "Saira",
    "Saladillo",
    "Saldán",
    "Salsacate",
    "Salsipuedes",
    "Sampacho",
    "San Agustín",
    "San Antonio de Arredondo",
    "San Antonio de Litín",
    "Santa Catalina",
    "Santa Eufemia",
    "Santiago Temple",
    "San Carlos Minas",
    "San Esteban",
    "San Francisco del Chañar",
    "San Gerónimo",
    "San Ignacio",
    "San Javier y Yacanto",
    "San Joaquín",
    "San José",
    "San José de la Dormida",
    "San José de las Salinas",
    "San Lorenzo",
    "San Marcos Sierras",
    "San Marcos Sud",
    "San Pedro",
    "San Pedro Norte",
    "San Roque",
    "Santa María de Punilla",
    "San Vicente",
    "Santa Rosa de Calamuchita",
    "Sarmiento",
    "Saturnino María Laspiur",
    "Sebastián Elcano",
    "Seeber",
    "Segunda Usina",
    "Serrano",
    "Villa Concepción del Tío",
    "Serrezuela",
    "Silvio Pellico",
    "Villa del Prado",
    "Sinsacate",
    "Suco",
    "Tala Cañada",
    "Tala Huasi",
    "Talaini",
    "Tinoco",
    "Tío Pujio",
    "Toro Pujio",
    "Toledo",
    "Tosno",
    "Villa la Bolsa",
    "Unquillo",
    "Valle Hermoso",
    "Villa Allende",
    "Villa Amancay",
    "Villa Rossi",
    "Villa Ascasubi",
    "Villa Candelaria Norte",
    "Villa San Esteban",
    "Villa Cerro Azul",
    "Villa Cura Brochero",
    "Villa de las Rosas",
    "Villa de María",
    "Villa de Pocho",
    "Villa de Soto",
    "Paso del Durazno",
    "Capilla del Monte",
    "Villa del Totoral",
    "Villa Dolores",
    "Villa Fontana",
    "Villa General Belgrano",
    "Villa Giardino",
    "Villa Huidobro",
    "Villa los Aromos",
    "Villa los Patos",
    "Cosquín",
    "Alta Gracia",
    "Colonia Videla",
    "Freyre",
    "Mina Clavero",
    "Adelia María",
    "Aldea Santa María",
    "Alejandro Roca",
    "Alejo Ledesma",
    "Alicia",
    "Arroyo Cabral",
    "Altos de Chipión",
    "Ana Zumarán",
    "Assunta",
    "Bulnes",
    "Calchín",
    "Calchín Oeste",
    "Chalacea",
    "Chancaní",
    "Chazón",
    "Cañada de Machado",
    "Cañada del Sauce",
    "Chucul",
    "Comechingones",
    "Cintra",
    "Colonia Almada",
    "Colonia Anita",
    "Colonia Barge",
    "Colonia Bismarck",
    "Colonia Valtelina",
    "Colonia Vicente Agüero",
    "Colonia Vignaud",
    "Cruz Alta",
    "Coronel Baigorria",
    "Corral de Bustos",
    "Cruz del Eje",
    "El Arañado",
    "Dalmacio Vélez",
    "Deán Funes",
    "El Brete",
    "El Tío",
    "Elena",
    "Eufrasio Loza",
    "General Baldissera",
    "General Roca",
    "Hernando",
    "Huanchilla",
    "Isla Verde",
    "Gütemberg",
    "Jovita",
    "Justiniano Posse",
    "Kilómetro 658",
    "La Batea",
    "Inriville",
    "Italó",
    "La Carlota",
    'La Carolina "El Potosi"',
    "Villa Parque Siquiman",
    "Córdoba",
    "La Playosa",
    "La Puerta",
    "La Quinta",
    "Las Calles",
    "Las Cañadas",
    "Las Perdices",
    "Las Peñas",
    "Las Peñas Sud",
    "Las Playas",
    "Las Saladas",
    "Las Gramillas",
    "Las Palmas",
    "Las Varas",
    "Las Varillas",
    "Los Cisnes",
    "Los Hoyos",
    "Los Molinos",
    "Los Surgentes",
    "Lutti",
    "Luca",
    "Lozada",
    "Marcos Juárez",
    "Mattaldi",
    "Mayu Sumaj",
    "Monte Leña",
    "Monte Maíz",
    "Noetinger",
    "Onagoity",
    "Pampayasta Sud",
    "Pascanas",
    "Punta del Agua",
    "Río Primero",
    "San Basilio",
    "San Clemente",
    "San Francisco",
    "Santa Elena",
    "Sauce Arriba",
    "Simbolar",
    "Tancacha",
    "Tanti",
    "Ticino",
    "Tosquita",
    "Tránsito",
    "Tuclame",
    "Ucacha",
    "Valle de Anisacate",
    "Viamonte",
    "Vicuña Mackenna",
    "Villa Ciudad Parque los Reartes",
    "Villa Carlos Paz",
    "Villa Ciudad de América",
    "Villa del Rosario",
    "Villa el Chacay",
    "Villa Elisa",
    "Villa Gutiérrez",
    "Villa Parque Santa Ana",
    "Villa Río Icho Cruz",
    "Villa Sarmiento (S. A.)",
    "Villa Tulumba",
    "Villa Valeria",
    "Wenceslao Escalante",
    "Villa María",
    "Villa Nueva",
    "Villa Quillinzo",
    "Villa Rumipal",
    "Villa San Isidro",
    "Villa Santa Cruz del Lago",
    "Santa Rosa de Río Primero",
    "Villa Sarmiento (G.R.)",
    "Washington",
    "Los Cóndores",
  ],
  [
    "General Alvear",
    "San Rafael",
    "Rivadavia",
    "Tupungato",
    "San Carlos",
    "Tunuyán",
    "Luján de Cuyo",
    "Las Heras",
    "Lavalle",
    "Malargüe",
    "Guaymallén",
    "Maipú",
    "Capital",
    "Godoy Cruz",
    "Junín",
    "San Martín",
    "Santa Rosa",
    "La Paz",
  ],
  [
    "General Ocampo",
    "Chamical",
    "Arauco",
    "General Lamadrid",
    "Vinchina",
    "Capital",
    "Coronel Felipe Varela",
    "Castro Barros",
    "Chilecito",
    "General Ángel Vicente Peñaloza",
    "General Juan Facundo Quiroga",
    "Rosario Vera Peñaloza",
    "General San Martín",
    "Famatina",
    "San Blas de los Sauces",
    "Independencia",
    "General Belgrano",
    "Sanagasta",
  ],
  [
    "Belén",
    "Hualfín",
    "Valle Viejo",
    "Ancasti",
    "Antofagasta de la Sierra",
    "Fiambalá",
    "Tinogasta",
    "Pozo de Piedra",
    "San Fernando",
    "Puerta de San José",
    "Puerta de Corral Quemado",
    "San José",
    "Santa María",
    "Aconquija",
    "Andalgalá",
    "Saujil",
    "Pomán",
    "Mutquín",
    "Santa Rosa",
    "Recreo",
    "San Fernando del Valle de Catamarca",
    "Icaño",
    "Paclín",
    "Tapso",
    "Londres",
    "Villa Vil",
    "Los Varela",
    "La Puerta",
    "Las Juntas",
    "El Rodeo",
    "Los Altos",
    "El Alto",
    "Huillapima",
    "Capayán",
    "Fray Mamerto Esquiú",
    "Corral Quemado",
  ],
  [
    "Pichi Huinca",
    "Quehué",
    "Abramo",
    "Santa Teresa",
    "General Campos",
    "Trenel",
    "Rancul",
    "Coronel Hilario Lagos",
    "Bernardo Larroude",
    "Ceballos",
    "Intendente Alvear",
    "Miguel Riglos",
    "Toay",
    "Puelén",
    "La Maruja",
    "Arata",
    "Sarah",
    "Ingeniero Luiggi",
    "Eduardo Castex",
    "Monte Nievas",
    "Quemú Quemú",
    "Villa Mirasol",
    "Colonia Barón",
    "Winifreda",
    "Loventué",
    "Santa Isabel",
    "Telén",
    "Ataliva Roca",
    "Bernasconi",
    "Victorica",
    "Metileo",
    "Uriburu",
    "Lonquimay",
    "Luan Toro",
    "Carro Quemado",
    "Perú",
    "Colonia Santa María",
    "Unanue",
    "Jacinto Arauz",
    "Chacharramendi",
    "Tomás Manuel Anchorena",
    "Relmo",
    "Santa Rosa",
    "La Reforma",
    "Limay Mahuida",
    "Gobernador Duval",
    "Falucho",
    "Alta Italia",
    "Anguil",
    "Mauricio Mayer",
    "General San Martín",
    "Casa de Piedra",
    "La Humada",
    "Cuchillo Có",
    "Doblas",
    "Parera",
    "Rucanelo",
    "Caleufú",
    "General Pico",
    "Agustoni",
    "Miguel Cané",
    "Puelches",
    "Algarrobo del Águila",
    "Vértiz",
    "Catriló",
    "Rolón",
    "Adolfo Van Praet",
    "Dorila",
    "Maisonnave",
    "Quetrequén",
    "Veinticinco de Mayo",
    "Macachín",
    "Embajador Martini",
    "Alpachiri",
    "Conhelo",
    "General Acha",
    "Guatraché",
    "Speluzzi",
    "La Adela",
    "Realicó",
  ],
  [
    "Rivadavia",
    "Juan F. Ibarra",
    "General Taboada",
    "Sarmiento",
    "Belgrano",
    "Aguirre",
    "Atamisqui",
    "Alberdi",
    "Ojo de Agua",
    "Choya",
    "Copo",
    "Río Hondo",
    "Banda",
    "Guasayán",
    "Robles",
    "Capital",
    "Loreto",
    "Silípica",
    "Figueroa",
    "Salavina",
    "Pellegrini",
    "Avellaneda",
    "Moreno",
    "Mitre",
    "Quebrachos",
    "San Martín",
    "Jiménez",
  ],
  [
    "Yataytí Calle",
    "Mercedes",
    "Saladas",
    "Juan Pujol",
    "Pueblo Libertador",
    "Monte Caseros",
    "Colonia Libertad",
    "Parada Pucheta",
    "Sauce",
    "Guaviraví",
    "Tapebicuá",
    "Lavalle",
    "Santa Lucía",
    "Paso de los Libres",
    "Goya",
    "Gobernador Martínez",
    "9 de Julio",
    "Felipe Yofré",
    "Chavarría",
    "Estación Torrent",
    "Pedro R. Fernández",
    "Tatacuá",
    "La Cruz",
    "Colonia Carlos Pellegrini",
    "Tabay",
    "Bella Vista",
    "Concepción",
    "Jose Rafael Gomez",
    "Palmar Grande",
    "Mburucuyá",
    "San Miguel",
    "Villa Olivari",
    "Gobernador Ing. Valentín Virasoro",
    "Lomas de Vallejos",
    "Empedrado",
    "San Antonio",
    "Colonia Liebig'S",
    "Riachuelo",
    "Herlitzka",
    "Caá Catí",
    "Loreto",
    "Itá Ibaté",
    "San Carlos",
    "Berón de Astrada",
    "Santa Ana",
    "San Luis del Palmar",
    "Corrientes",
    "Ramada Paso",
    "San Cosme",
    "Paso de la Patria",
    "Mocoretá",
    "San Isidro",
    "Esquina",
    "Curuzú Cuatiá",
    "Bonpland",
    "Yapeyú",
    "Mariano I. Loza",
    "Garruchos",
    "Carolina",
    "Perugorría",
    "Cruz de los Milagros",
    "Alvear",
    "Colonia Pando",
    "San Roque",
    "Itatí",
    "Ituzaingó",
    "San Lorenzo",
    "Colonia Santa Rosa",
    "Santo Tomé",
  ],
  [
    "Pavón",
    "Huanqueros",
    "Arroyo Ceibal",
    "Villa Ana",
    "Aguará Grande",
    "Angeloni",
    "San Mart",
    "Videla",
    "Colonia Dolores",
    "Saladero Mariano Cabal",
    "Helvecia",
    "Colonia Mascias",
    "Pueblo Irigoyen",
    "Coronda",
    "Casalegno",
    "Cañada Rosquín",
    "Colonia Bigand",
    "Pavón Arriba",
    "Melincué",
    "Dos Rosas y la Legua",
    "Colonia Bossi",
    "Las Avispas",
    "Serodino",
    "San Jerónimo Sud",
    "Theobald",
    "Gregoria Pérez de Denis",
    "Barrancas",
    "Monje",
    "Constanza",
    "San Genaro",
    "Sauce Viejo",
    "Santa Margarita",
    "Gato Colorado",
    "San Antonio de Obligado",
    "Tacuarendí",
    "Colonia Durán",
    "Villa Guillermina",
    "Florencia",
    "Bella Italia",
    "Las Palmeras",
    "Venado Tuerto",
    "El Rabón",
    "Las Toscas",
    "Avellaneda",
    "Cañada Ombú",
    "San Bernardo",
    "Fortín Olmos",
    "San Guillermo",
    "Curupaity",
    "Arrufo",
    "La Rubia",
    "Colonia Ana",
    "Villa Trinidad",
    "Palacios",
    "Monigotes",
    "Ambrosetti",
    "La Lucila",
    "Capivara",
    "Colonia la Clara",
    "Montefiore",
    "La Sarita",
    "Tartagal",
    "Malabrigo",
    "Berna",
    "Nicanor Molinas",
    "Juan de Garay",
    "Hersilia",
    "Ceres",
    "La Cabral",
    "San Cristóbal",
    "La Criolla",
    "Vera y Pintado",
    "Intiyaco",
    "La Penca y Caraguatá",
    "Villa Saralegui",
    "Calchaquí",
    "Pozo Borrado",
    "El Arazá",
    "La Gallareta",
    "Toba",
    "Cayastacito",
    "Esther",
    "Pedro Gómez Cello",
    "Hugentobler",
    "Pueblo Marini",
    "Colonia Aldao",
    "Fidela",
    "Vila",
    "Coronel Fraga",
    "San Antonio",
    "Santa Clara de Saguier",
    "Saguier",
    "Villa San José",
    "Rafaela",
    "Estación Clucellas",
    "Angélica",
    "Santa María Centro",
    "Colonia Cello",
    "Josefina",
    "Frontera",
    "Tacurales",
    "Eusebia y Carolina",
    "María Juana",
    "Garibaldi",
    "Esmeralda",
    "Castelar",
    "San Vicente",
    "Ramona",
    "Bauer y Sigel",
    "San Mart",
    "San Jorge",
    "Crispi",
    "Aurelia",
    "Carlos Pellegrini",
    "Casas",
    "El Trébol",
    "María Susana",
    "Los Cardos",
    "Las Bandurrias",
    "Colonia Margarita",
    "Sastre",
    "Las Petacas",
    "Centeno",
    "Gálvez",
    "Santa Clara de Buena Vista",
    "López",
    "Campo Piaggio",
    "Loma Alta",
    "Fuentes",
    "Gessler",
    "Sa Pereyra",
    "San Agustín",
    "San Carlos Sud",
    "San Mariano",
    "Matilde",
    "Díaz",
    "Maciel",
    "San Eugenio",
    "Santo Tomé",
    "Empalme San Carlos",
    "San José del Rincón",
    "Pilar",
    "Monte Vera",
    "Lucio V. López",
    "Recreo",
    "Nuevo Torino",
    "Humboldt",
    "Santa Rosa de Calchines",
    "Fighiera",
    "Cayastá",
    "Arroyo Aguiar",
    "Cululú",
    "Progreso",
    "Candioti",
    "Campo Andino",
    "Romang",
    "Desvío Arijón",
    "Laguna Paiva",
    "Nelson",
    "Rivadavia",
    "Grutly",
    "Felicia",
    "Lehmann",
    "Hipatía",
    "Soutomayor",
    "Llambi Campbell",
    "Tacural",
    "Cabal",
    "Montes de Oca",
    "Emilia",
    "Santo Domingo",
    "María Luisa",
    "La Pelada",
    "Providencia",
    "Ituzaingó",
    "Jacinto L. Arauz",
    "Humberto Primo",
    "Colonia Bicha",
    "Sunchales",
    "Colonia Belgrano",
    "Bouquet",
    "Las Parejas",
    "Totoras",
    "Bustinza",
    "Roldán",
    "Tortugas",
    "Armstrong",
    "Pueblo Andino",
    "Diego de Alvear",
    "San Gregorio",
    "Christophersen",
    "Aldao",
    "Piñero",
    "Villa Eloísa",
    "Juncal",
    "Alcorta",
    "Peyrano",
    "Cañada Rica",
    "Sargento Cabral",
    "Cepeda",
    "Los Molinos",
    "Arequito",
    "San José de la Esquina",
    "Sanford",
    "Arteaga",
    "Álvarez",
    "Acebal",
    "Uranga",
    "Rueda",
    "Juan Bernabé Molina",
    "Villa Mugueta",
    "Arminda",
    "Carcarañá",
    "Chañar Ladeado",
    "Berabevú",
    "Los Quirquinchos",
    "La Chispa",
    "Chabas",
    "Murphy",
    "Villada",
    "Cañada del Ucle",
    "Firmat",
    "Bombal",
    "Carreras",
    "Labordeboy",
    "Hughes",
    "Villa Cañás",
    "Chovet",
    "Elortondo",
    "Santa Isabel",
    "Carmen",
    "Gödeken",
    "María Teresa",
    "Maggiolo",
    "San Francisco de Santa Fe",
    "San Eduardo",
    "Miguel Torres",
    "Bigand",
    "Chapuy",
    "Santa Teresa",
    "Cañada de Gómez",
    "Coronel Bogado",
    "Coronel Arnold",
    "Zavalla",
    "Granadero Baigorria",
    "Carrizales",
    "San Lorenzo",
    "Fray Luis Beltrán",
    "Capitán Bermúdez",
    "Ibarlucea",
    "General Lagos",
    "Villa Amelia",
    "Alvear",
    "Villa Constitución",
    "Gaboto",
    "El Sombrerito",
    "Alejandra",
    "Guadalupe Norte",
    "Egusquiza",
    "Ricardone",
    "Pujato",
    "Salto Grande",
    "Aarón Castellanos",
    "Arocena",
    "Golondrina",
    "San Bernardo",
    "Susana",
    "Esteban Rams",
    "La Camila",
    "Monte Oscuridad",
    "Suardi",
    "La Brava",
    "Silva",
    "Marcelino Escalada",
    "Ramayón",
    "Cacique Ariacaiquín",
    "San Justo",
    "Los Amores",
    "Las Garzas",
    "Vera",
    "San Fabián",
    "La Vanguardia",
    "Reconquista",
    "Colonia Rosa",
    "Moisés Ville",
    "Villa Minetti",
    "Ñanducita",
    "Santa Fe",
    "Santurce",
    "Soledad",
    "Tostado",
    "Logroño",
    "Esperanza",
    "Arroyo Leyes",
    "Portugalete",
    "Naré",
    "Gobernador Crespo",
    "Castellanos",
    "Garabato",
    "Margarita",
    "Lanteri",
    "Ingeniero Chanourdie",
    "Presidente Roca",
    "Plaza Clucellas",
    "Zenón Pereyra",
    "Eustolia",
    "Los Laureles",
    "San Javier",
    "Traill",
    "Piamonte",
    "Colonia Iturraspe",
    "Correa",
    "Landeta",
    "Bernardo de Irigoyen",
    "Colonia San José",
    "M9Ximo Paz",
    "General Gelly",
    "Franck",
    "Las Tunas",
    "San Jerónimo del Sauce",
    "San Carlos Centro",
    "San Carlos Norte",
    "Larrechea",
    "San Jerónimo Norte",
    "Santa María Norte",
    "Pujato Norte",
    "Pueblo Muñoz",
    "Cavour",
    "Virginia",
    "Ataliva",
    "Galisteo",
    "Sarmiento",
    "Timbúes",
    "Elisa",
    "Maua",
    "Las Rosas",
    "Rufino",
    "Colonia Raquel",
    "Lazzarino",
    "Amenábar",
    "Clason",
    "Casilda",
    "Teodelina",
    "Wheelwright",
    "Funes",
    "Pérez",
    "Albarellos",
    "Coronel Domínguez",
    "Empalme Villa Constitución",
    "Godoy",
    "Cafferata",
    "Sancti Spiritu",
    "Carmen del Sauce",
    "Soldini",
    "Luis Palacios",
    "Villa Gobernador Gálvez",
    "Oliveros",
    "Pueblo Esther",
    "Arroyo Seco",
  ],
  [
    "Manuel Garcia Fernandez",
    "San Jose de la Cocha",
    "Yanima",
    "El Mollar",
    "Municipalidad de Tafi del Valle",
    "Municipalidad de la Cocha",
    "El Sacrificio",
    "San Pedro y San Antonio",
    "Gastona y Belicha",
    "Municipalidad de Concepcion",
    "Pampa Mayo",
    "Alpachiri y el Molino",
    "Arcadia",
    "Villa Quinteros",
    "Capitan Caceres",
    "Soldado Maldonado",
    "Los Sosa",
    "Municipalidad de Simoca",
    "El Timbo",
    "Ancajuli",
    "Los Nogales",
    "El Naranjo y el Sunchal",
    "La Esperanza",
    "El Cadillal",
    "Tapia",
    "Yerba Buena",
    "Municipalidad de las Talitas",
    "Los Puestos",
    "El Puestito",
    "Atahona",
    "El Bracho y el Cevilar",
    "El Naranjito",
    "San Pablo y Villa Nougues",
    "Santa Lucia",
    "Municipalidad de Lules",
    "Comuna Villa Belgrano",
    "Delfin Gallo",
    "Municipalidad de Alderetes",
    "Municipalidad de Graneros",
    "Acheral",
    "Rio Colorado",
    "Municipalidad de San Miguel De Tucuman",
    "Amberes",
    "Santa Cruz y la Tuna",
    "Raco",
    "Buena Vista",
    "Rumipunco",
    "Teniente Berdina",
    "Choromoro",
    "Municipalidad de Trancas",
    "San Pedro de Colalao",
    "Quilmes y los Sueldos",
    "Los Gomez",
    "Esquina y Mancopa",
    "San Ignacio",
    "Manuela Pedraza",
    "Colombres",
    "Agua Dulce y la Soledad",
    "Gdor. Piedrabuena",
    "San Javier",
    "Municipalidad de Juan Bautista Alberdi",
    "Monteagudo",
    "El Polear",
    "Santa Ana",
    "Villa de Chicligasta",
    "Trinidad",
    "Ciudacita",
    "Rio Chico y Nueva Trinidad",
    "Municipalidad de Aguilares",
    "Los Sarmiento y la Tipa",
    "Monte Bello",
    "Sargento Moya",
    "Rio Seco",
    "San Andres",
    "Lamadrid",
    "San Felipe y Santa Barbara",
    "Amaicha del Valle",
    "Municipalidad de Yerba Buena",
    "Villa Padre Monti",
    "Los Ralos",
    "Taco Ralo",
    "Colalao del Valle",
    "Cevil Redondo",
    "Ranchillos y San Miguel",
    "El Chañar",
    "La Florida y Luisiana",
    "La Ramada y la Cruz",
    "Los Perez",
    "Estacion Araoz y Tacanas",
    "El Mojon",
    "Benjamin Araoz y el Tajamar",
    "Los Pereyras",
    "Garmendia",
    "Las Cejas",
    "Municipalidad de Monteros",
    "7 de Abril",
    "Municipalidad de Bella Vista",
    "Villa de Leales",
    "Santa Rosa de Leales y L. Blanca",
    "Las Talas",
    "Huasa Pampa",
    "Escaba",
    "Leon Rouges y Santa Rosa",
    "Municipalidad de Tafi Viejo",
    "Medina",
    "Alto Verde y los Guchea",
    "Municipalidad de Burruyacu",
    "Los Bulacios y los Villagras",
    "Municipalidad de Banda del Rio Sali",
    "El Cercado",
    "Municipalidad de Famailla",
    "El Manantial",
  ],
  [
    "Guañacos",
    "Rincón de los Sauces",
    "Octavio Pico",
    "Buta Ranquil",
    "Barrancas",
    "Añelo",
    "Quili Malal",
    "Las Lajas",
    "Zapala",
    "Mariano Moreno",
    "Senillosa",
    "Junín de los Andes",
    "Aluminé",
    "Villa Traful",
    "Caviahue-Copahue",
    "Neuquén",
    "Plottier",
    "Centenario",
    "Vista Alegre",
    "San Patricio del Chañar",
    "Villa el Chocón",
    "Cutral Có",
    "Plaza Huincul",
    "El Sauce",
    "Picún Leufú",
    "Las Coloradas",
    "Santo Tomás",
    "Los Miches",
    "El Huecú",
    "Loncopué",
    "Bajada del Agrio",
    "Tricao Malal",
    "Villa Curi Leuvú",
    "Huinganco",
    "Varvarco - Invernada Vieja",
    "Los Chihuidos",
    "Ramón Castro",
    "Covunco Abajo",
    "Pilo Lil",
    "Coyuco-Cochico",
    "Los Catutos",
    "Sauzal Bonito",
    "San Martín de los Andes",
    "Villa Pehuenia",
    "Piedra del Águila",
    "Villa del Nahueve",
    "Andacollo",
    "El Cholar",
    "Taquimilán",
    "Chos Malal",
    "Manzano Amargo",
    "Chorriaca",
    "Villa del Puente Picún Leufú",
    "Aguada San Roque",
    "Paso Aguerre",
    "Las Ovejas",
    "Villa la Angostura",
  ],
  [
    "La Merced",
    "Las Lajitas",
    "Tolar Grande",
    "Cafayate",
    "Cerrillos",
    "Embarcación",
    "Río Piedras",
    "General Güemes",
    "Santa Victoria Este",
    "Campo Quijano",
    "Angastaco",
    "Aguaray",
    "Santa Victoria Oeste",
    "Nazareno",
    "El Bordo",
    "Guachipas",
    "Animaná",
    "Metán",
    "San Lorenzo",
    "Campo Santo",
    "El Tala",
    "La Candelaria",
    "San Ramón de la Nueva Orán",
    "Seclantás",
    "Apolinario Saravia",
    "General Mosconi",
    "Los Toldos",
    "Coronel Moldes",
    "Pichanal",
    "Tartagal",
    "General Ballivián",
    "Joaquín V. González",
    "General Pizarro",
    "Salta",
    "Vaqueros",
    "El Quebrachal",
    "Rosario de Lerma",
    "El Carril",
    "Rivadavia Banda Sur",
    "Payogasta",
    "Cachi",
    "Colonia Santa Rosa",
    "El Jardín",
    "San Antonio de los Cobres",
    "Molinos",
    "Rivadavia Banda Norte",
    "Profesor Salvador Mazza",
    "El Potrero",
    "Hipólito Yrigoyen",
    "Iruya",
    "Chicoana",
    "San Carlos",
    "La Poma",
    "Urundel",
    "La Viña",
    "Isla de Cañas",
    "Rosario de la Frontera",
    "La Caldera",
    "El Galpón",
  ],
  [
    "Isla del Cerrito",
    "Chorotis",
    "Santa Sylvina",
    "Coronel Du Graty",
    "Hermoso Campo",
    "Samuhú",
    "Basail",
    "Puerto Vilelas",
    "Villa Ángela",
    "Fontana",
    "Barranqueras",
    "General Capdevila",
    "Cote Lai",
    "Puerto Tirol",
    "Colonia Popular",
    "San Bernardo",
    "Makallé",
    "Juan José Castelli",
    "Miraflores",
    "Laguna Blanca",
    "Lapachito",
    "La Clotilde",
    "Gancedo",
    "La Escondida",
    "Villa Berthet",
    "La Verde",
    "La Tigra",
    "Las Palmas",
    "General Pinedo",
    "Capitán Solari",
    "Puerto Bermejo",
    "Presidencia de la Plaza",
    "Campo Largo",
    "Corzuela",
    "Puerto Eva Perón",
    "Napenay",
    "La Eduvigis",
    "Presidencia Roque Sáenz Peña",
    "Las Garcitas",
    "Pampa Almirón",
    "Ciervo Petiso",
    "Avia Terai",
    "Laguna Limpia",
    "Gral. San Martengeneral San Martín",
    "Machagai",
    "Concepción del Bermejo",
    "Pampa del Infierno",
    "Presidencia Roca",
    "Pampa del Indio",
    "Los Frentones",
    "Tres Isletas",
    "Villa Río Bermejito",
    "Misión Nueva Pompeya",
    "Fuerte Esperanza",
    "El Sauzalito",
    "Colonia Benitez",
    "Colonias Elisa",
    "Colonias Unidas",
    "General Vedia",
    "Resistencia",
    "Enrique Urien",
    "Charadai",
    "Margarita Belén",
    "La Leonesa",
    "Charata",
    "Las Breñas",
    "Quitilipi",
    "Taco Pozo",
  ],
  [
    "Fortín Lugones",
    "Villa Dos Trece",
    "San Hilario",
    "General Güemes",
    "General Belgrano",
    "Misión Taacaglé",
    "Buena Vista",
    "Laguna Blanca",
    "Laguna Naik Neck",
    "Riacho He-He",
    "Colonia Pastoril",
    "General Mosconi",
    "Ingeniero Guillermo N. Juárez",
    "Los Chiriguanos",
    "Las Lomitas",
    "Pozo del Tigre",
    "Estanislao del Campo",
    "Ibarreta",
    "Comandante Fontana",
    "Palo Santo",
    "Pirané",
    "Gran Guardia",
    "Subteniente Perín",
    "Formosa",
    "El Colorado",
    "Villa Escolar",
    "San Martín Dos",
    "Misión San Francisco de Laishí",
    "Herradura",
    "General Lucio Victorio Mansilla",
    "Espinillo",
    "Siete Palmas",
    "Clorinda",
    "Portón Negro",
    "Tres Lagunas",
    "Laguna Yema",
    "Mayor Vicente E. Villafañe",
  ],
  [
    "Yavi",
    "El Cóndor",
    "Cangrejillos",
    "Abra Pampa",
    "Tres Cruces",
    "Abralaite",
    "Humahuaca",
    "Abdón Castro Tolay",
    "Coranzuli",
    "El Aguilar",
    "Susques",
    "Caspalá",
    "Santa Ana",
    "Huacalera",
    "Catua",
    "Pampichuela",
    "Valle Grande",
    "Yuto",
    "El Talar",
    "Maimará",
    "Calilegua",
    "Vinalito",
    "Libertador General San Martín",
    "Fraile Pintado",
    "Palpalá",
    "San Salvador de Jujuy",
    "Arrayanal",
    "La Esperanza",
    "El Fuerte",
    "Rodeíto",
    "Santa Clara",
    "La Mendieta",
    "San Antonio",
    "Rosario de Río Grande",
    "El Carmen",
    "Perico",
    "Puesto Viejo",
    "Monterrico",
    "Pampa Blanca",
    "Aguas Calientes",
    "Barrios",
    "Rinconada",
    "Santa Catalina",
    "Cieneguillas",
    "La Quiaca",
    "Cusi Cusi",
    "Pumahuasi",
    "Mina Pirquitas",
    "Puesto del Marqués",
    "Hipólito Yrigoyen",
    "Caimancito",
    "Purmamarca",
    "Tilcara",
    "San Francisco",
    "Tumbaya",
    "Volcán",
    "Palma Sola",
    "Yala",
    "El Piquete",
    "San Pedro de Jujuy",
  ],
  [
    "CIUDAD DE BUENOS AIRES",
    "CONSTITUCION",
    "MONSERRAT",
    "PUERTO MADERO",
    "RETIRO",
    "SAN NICOLAS",
    "SAN TELMO",
    "RECOLETA",
    "BALVANERA",
    "SAN CRISTOBAL",
    "BARRACAS",
    "BOCA",
    "NUEVA POMPEYA",
    "PARQUE PATRICIOS",
    "ALMAGRO",
    "BOEDO",
    "CABALLITO",
    "FLORES",
    "PARQUE CHACABUCO",
    "VILLA LUGANO",
    "VILLA RIACHUELO",
    "VILLA SOLDATI",
    "LINIERS",
    "MATADEROS",
    "PARQUE AVELLANEDA",
    "FLORESTA",
    "MONTE CASTRO",
    "VELEZ SARSFIELD",
    "VERSALLES",
    "VILLA LURO",
    "VILLA REAL",
    "VILLA DEL PARQUE",
    "VILLA DEVOTO",
    "VILLA GENERAL MITRE",
    "VILLA SANTA RITA",
    "COGHLAN",
    "SAAVEDRA",
    "VILLA PUEYRREDON",
    "VILLA URQUIZA",
    "BELGRANO",
    "COLEGIALES",
    "NUÑEZ",
    "PALERMO",
    "AGRONOMIA",
    "CHACARITA",
    "PARQUE CHAS",
    "PATERNAL",
    "VILLA CRESPO",
    "VILLA ORTUZAR",
  ],
  [
    "Bahía Blanca",
    "General Alvarado",
    "General Pueyrredón",
    "Mar Chiquita",
    "Pinamar",
    "Magdalena",
    "Vicente López",
    "Pergamino",
    "Rauch",
    "Salliqueló",
    "Coronel Pringles",
    "Saladillo",
    "Las Flores",
    "Rojas",
    "Escobar",
    "Bolívar",
    "José C. Paz",
    "Maipú",
    "La Matanza",
    "San Antonio de Areco",
    "Moreno",
    "General Paz",
    "General Guido",
    "General Juan Madariaga",
    "Tandil",
    "Coronel Suárez",
    "Adolfo Gonzales Chaves",
    "Villa Gesell",
    "General Lavalle",
    "La Costa",
    "Berazategui",
    "Tornquist",
    "Tigre",
    "Adolfo Alsina",
    "Pellegrini",
    "Villarino",
    "Puán",
    "General Villegas",
    "Castelli",
    "Almirante Brown",
    "La Plata",
    "Presidente Perón",
    "Brandsen",
    "Carlos Casares",
    "Carlos Tejedor",
    "9 de Julio",
    "Pehuajó",
    "Trenque Lauquen",
    "Roque Pérez",
    "Olavarría",
    "Arrecifes",
    "Capitán Sarmiento",
    "Carmen de Areco",
    "Salto",
    "Merlo",
    "Esteban Echeverría",
    "Exaltación de la Cruz",
    "San Miguel",
    "Pilar",
    "Luján",
    "Junín",
    "Chacabuco",
    "Mercedes",
    "Hurlingham",
    "General Rodríguez",
    "Morón",
    "Lincoln",
    "Ituzaingó",
    "Suipacha",
    "Marcos Paz",
    "Tres de Febrero",
    "Chivilcoy",
    "Alberti",
    "Bragado",
    "Lanús",
    "General las Heras",
    "Lomas de Zamora",
    "Florencio Varela",
    "Quilmes",
    "Pila",
    "Navarro",
    "Cañuelas",
    "San Vicente",
    "General la Madrid",
    "Benito Juárez",
    "Balcarce",
    "Azul",
    "Guaminí",
    "Tordillo",
    "Avellaneda",
    "San Isidro",
    "Patagones",
    "Coronel de Marina Leonardo Rosales",
    "Colón",
    "Saavedra",
    "Monte Hermoso",
    "Lobería",
    "Berisso",
    "San Fernando",
    "Zárate",
    "Ramallo",
    "San Nicolás",
    "General Arenales",
    "Florentino Ameghino",
    "San Pedro",
    "General Pinto",
    "San Cayetano",
    "Tres Arroyos",
    "Coronel Dorrego",
    "Necochea",
    "Lezama",
    "Chascomús",
    "Punta Indio",
    "Campana",
    "25 de Mayo",
    "General Belgrano",
    "Monte",
    "Lobos",
    "General Alvear",
    "Tapalqué",
    "Tres Lomas",
    "Ayacucho",
    "General San Martín",
    "Malvinas Argentinas",
    "San Andrés de Giles",
    "General Viamonte",
    "Daireaux",
    "Ezeiza",
    "Rivadavia",
    "Hipólito Yrigoyen",
    "Dolores",
    "Ensenada",
    "Laprida",
    "Leandro N. Alem",
    "Baradero",
  ],
  ["Río Grande", "Tolhuin", "Ushuaia"],
];

module.exports = {
  validateDataBase,
  examplePets,
  ejemplosUsers,
  ejemploProvincias,
  ejemploLocalidades,
};
